# Site
name: "Studio HB"
title: "Studio HB"
description: "Studio HB, l’agence web spécialisée dans le développement sur mesure."
logo: 'assets/images/ruby.svg'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: ''
disqus: 'blog-6jsclhfa9v'
mailchimp-list: false
include: ["_pages", "_redirects"]
permalink: /:title/

# Authors
authors:
  guillaumebriday:
    name: Guillaume Briday
    display_name: Guillaume Briday
    gravatar: 052f1039a54fc4970b24a038c1fa507b
    email: guillaumebriday@gmail.com
    web: https://guillaumebriday.fr/
    twitter: https://twitter.com/guillaumebriday
    description: ""

  mariebodin:
    name: Marie Bodin
    display_name: Marie Bodin
    gravatar: 6758f1339587fa9f2cdb83f91870092e
    email: m.bodin@studio-hb.com
    description: "Passionnée par le digital et soucieuse de l’impact que nos métiers peuvent avoir sur la société"

  laurentbuffevant:
    name: Laurent Buffevant
    display_name: Laurent Buffevant
    gravatar: 9319462d322e93c6914ef1e6ab3b95af
    email: l.buffevant@studio-hb.com
    web: https://www.studio-hb.com/
    twitter: https://twitter.com/studiohb
    description: ""

  lucasbiguetmermet:
    name: Lucas Biguet-Mermet
    display_name: Lucas Biguet-Mermet
    gravatar: 6da41b3b67bb76b3b84708b8cb9f66d4
    email: l.biguet-mermet@studio-hb.com
    web: https://www.studio-hb.com/
    description: ""

  charlottemassanes:
    name: Charlotte Massanès
    display_name: Charlotte Massanès
    gravatar: f3be2802b49fa0418bc97612d3cb96ab
    email: c.massanes@studio-hb.com
    web: https://www.studio-hb.com/
    description: ""

  celinechamiot:
    name: Céline Chamiot-Poncet
    display_name: Céline Chamiot-Poncet
    gravatar: 518ed0e62781bf9b812b2999ffc7e8da
    email: c.chamiot@studio-hb.com
    web: https://www.studio-hb.com/
    description: ""

  gregoiredief:
    name: Grégoire Dief
    display_name: Grégoire Dief
    gravatar: 5308c6578a67fbfe04e9b03c5fd13289
    email: g.dief@studio-hb.com
    web: https://www.studio-hb.com/
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-admin

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 30
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
